<a href="https://colab.research.google.com/github/elkhaa151105-droid/pm-turi2-preprocessing-khaerultamam/blob/main/PM_P4_KHAERUL_TAMAM_2488010023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:

import pandas as pd
import numpy as np

data = {
    'usia': [25, 32, np.nan, 45, 28, 51, 38, np.nan, 29, 41],

    'pendapatan': [
        4_000_000, 7_500_000, 5_200_000, 12_000_000, 4_800_000,
        15_000_000, 8_100_000, 6_300_000, np.nan, 9_900_000
    ],

    'pendidikan': [
        'SMA', 'S1', 'SMA', 'S2', 'SMA',
        'S2', 'S1', 'S1', 'SMA', 'S2'
    ],

    'kota': [
        'Bandung', 'Jakarta', 'Bandung', 'Surabaya', 'Jakarta',
        'Surabaya', 'Jakarta', 'Bandung', 'Bandung', 'Jakarta'
    ],

    'membeli': [
        'Tidak', 'Ya', 'Tidak', 'Ya', 'Tidak',
        'Ya', 'Ya', 'Tidak', 'Tidak', 'Ya'
    ]
}

df = pd.DataFrame(data)

# Menampilkan dataset awal
df

   usia  pendapatan pendidikan      kota membeli
0  25.0   4000000.0        SMA   Bandung   Tidak
1  32.0   7500000.0         S1   Jakarta      Ya
2   NaN   5200000.0        SMA   Bandung   Tidak
3  45.0  12000000.0         S2  Surabaya      Ya
4  28.0   4800000.0        SMA   Jakarta   Tidak
5  51.0  15000000.0         S2  Surabaya      Ya
6  38.0   8100000.0         S1   Jakarta      Ya
7   NaN   6300000.0         S1   Bandung   Tidak
8  29.0         NaN        SMA   Bandung   Tidak
9  41.0   9900000.0         S2   Jakarta      Ya

In [31]:
df['usia'] = df['usia'].fillna(df['usia'].median())
df['pendapatan'] = df['pendapatan'].fillna(df['pendapatan'].median())
df.isnull().sum()

usia          0
pendapatan    0
pendidikan    0
kota          0
membeli       0
dtype: int64

In [32]:
X = df.drop(columns=['membeli'])
y = df['membeli']

print("X:")
display(X)

print("y:")
display(y)

X:

   usia  pendapatan pendidikan      kota
0  25.0   4000000.0        SMA   Bandung
1  32.0   7500000.0         S1   Jakarta
2  35.0   5200000.0        SMA   Bandung
3  45.0  12000000.0         S2  Surabaya
4  28.0   4800000.0        SMA   Jakarta
5  51.0  15000000.0         S2  Surabaya
6  38.0   8100000.0         S1   Jakarta
7  35.0   6300000.0         S1   Bandung
8  29.0   7500000.0        SMA   Bandung
9  41.0   9900000.0         S2   Jakarta

y:

0    Tidak
1       Ya
2    Tidak
3       Ya
4    Tidak
5       Ya
6       Ya
7    Tidak
8    Tidak
9       Ya
Name: membeli, dtype: object

In [33]:
X['pendidikan'] = X['pendidikan'].map({'SMA': 0, 'S1': 1, 'S2': 2})  # ordinal

X = pd.get_dummies(X, columns=['kota'], dtype=int)  # nominal

y = y.map({'Tidak': 0, 'Ya': 1})

print("X setelah encoding:")
display(X)

print("y setelah encoding:")
display(y)

X setelah encoding:

   usia  pendapatan  pendidikan  kota_Bandung  kota_Jakarta  kota_Surabaya
0  25.0   4000000.0           0             1             0              0
1  32.0   7500000.0           1             0             1              0
2  35.0   5200000.0           0             1             0              0
3  45.0  12000000.0           2             0             0              1
4  28.0   4800000.0           0             0             1              0
5  51.0  15000000.0           2             0             0              1
6  38.0   8100000.0           1             0             1              0
7  35.0   6300000.0           1             1             0              0
8  29.0   7500000.0           0             1             0              0
9  41.0   9900000.0           2             0             1              0

y setelah encoding:

0    0
1    1
2    0
3    1
4    0
5    1
6    1
7    0
8    0
9    1
Name: membeli, dtype: int64

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (7, 6)
X_test : (3, 6)
y_train: (7,)
y_test : (3,)

In [35]:
from sklearn.preprocessing import StandardScaler
num = ['usia', 'pendapatan', 'pendidikan']
sc = StandardScaler()
X_train[num] = sc.fit_transform(X_train[num])
X_test[num] = sc.transform(X_test[num])

In [36]:
#mengecek nilai hilang
print("Nilai hilang pada X_train:")
print(X_train.isnull().sum())

print("\nNilai hilang pada X_test:")
print(X_test.isnull().sum())

Nilai hilang pada X_train:
usia             0
pendapatan       0
pendidikan       0
kota_Bandung     0
kota_Jakarta     0
kota_Surabaya    0
dtype: int64

Nilai hilang pada X_test:
usia             0
pendapatan       0
pendidikan       0
kota_Bandung     0
kota_Jakarta     0
kota_Surabaya    0
dtype: int64

In [37]:
#mengecek tipe data
print("Tipe data X_train:")
print(X_train.dtypes)

print("\nTipe data X_test:")
print(X_test.dtypes)

Tipe data X_train:
usia             float64
pendapatan       float64
pendidikan       float64
kota_Bandung       int64
kota_Jakarta       int64
kota_Surabaya      int64
dtype: object

Tipe data X_test:
usia             float64
pendapatan       float64
pendidikan       float64
kota_Bandung       int64
kota_Jakarta       int64
kota_Surabaya      int64
dtype: object

In [38]:
#melihat hasil scaling
print("Statistik X_train setelah scaling:")
display(X_train.describe())

Statistik X_train setelah scaling:

,usia,pendapatan,pendidikan,kota_Bandung,kota_Jakarta,kota_Surabaya
count,7.000000e+00,7.000000e+00,7.000000e+00,7.000000,7.000000,7.000000
mean,1.110223e-16,1.030921e-16,-1.982541e-17,0.428571,0.428571,0.142857
std,1.080123e+00,1.080123e+00,1.080123e+00,0.534522,0.534522,0.377964
min,-1.588665e+00,-1.169416e+00,-1.028992e+00,0.000000,0.000000,0.000000
25%,-5.847169e-01,-8.023348e-01,-1.028992e+00,0.000000,0.000000,0.000000
50%,-4.412958e-02,-3.251291e-01,1.714986e-01,0.000000,0.000000,0.000000
75%,6.509113e-01,6.659903e-01,7.717436e-01,1.000000,1.000000,0.000000
max,1.500406e+00,1.767234e+00,1.371989e+00,1.000000,1.000000,1.000000

In [39]:
print("X_train:")
display(X_train)

print("X_test:")
display(X_test)

print("y_train:")
display(y_train)

print("y_test:")
display(y_test)

X_train:

       usia  pendapatan  pendidikan  kota_Bandung  kota_Jakarta  kota_Surabaya
0 -1.588665   -1.169416   -1.028992             1             0              0
7 -0.044130   -0.325129    0.171499             1             0              0
2 -0.044130   -0.728919   -1.028992             1             0              0
9  0.882592    0.996363    1.371989             0             1              0
4 -1.125304   -0.875751   -1.028992             0             1              0
3  1.500406    1.767234    1.371989             0             0              1
6  0.419231    0.335617    0.171499             0             1              0

X_test:

       usia  pendapatan  pendidikan  kota_Bandung  kota_Jakarta  kota_Surabaya
8 -0.970851    0.115368   -1.028992             1             0              0
1 -0.507490    0.115368    0.171499             0             1              0
5  2.427127    2.868478    1.371989             0             0              1

y_train:

0    0
7    0
2    0
9    1
4    0
3    1
6    1
Name: membeli, dtype: int64

y_test:

8    0
1    1
5    1
Name: membeli, dtype: int64

Ganti imputasi usia menjadi mean

In [42]:
df_mean = pd.DataFrame(data)
df_mean['usia'] = df_mean['usia'].fillna(df_mean['usia'].mean())
df_mean['pendapatan'] = df_mean['pendapatan'].fillna(df_mean['pendapatan'].median())

print("Data setelah imputasi mean:")
display(df_mean)

print("Mean usia:", df['usia'].mean())
print("Median usia:", df['usia'].median())

# Data awal
df_perbandingan = pd.DataFrame(data)

# Imputasi usia dengan median
df_perbandingan['usia_median'] = df_perbandingan['usia'].fillna(df_perbandingan['usia'].median())

# Imputasi usia dengan mean
df_perbandingan['usia_mean'] = df_perbandingan['usia'].fillna(df_perbandingan['usia'].mean())

display(df_perbandingan[['usia', 'usia_median', 'usia_mean']])

Data setelah imputasi mean:

     usia  pendapatan pendidikan      kota membeli
0  25.000   4000000.0        SMA   Bandung   Tidak
1  32.000   7500000.0         S1   Jakarta      Ya
2  36.125   5200000.0        SMA   Bandung   Tidak
3  45.000  12000000.0         S2  Surabaya      Ya
4  28.000   4800000.0        SMA   Jakarta   Tidak
5  51.000  15000000.0         S2  Surabaya      Ya
6  38.000   8100000.0         S1   Jakarta      Ya
7  36.125   6300000.0         S1   Bandung   Tidak
8  29.000   7500000.0        SMA   Bandung   Tidak
9  41.000   9900000.0         S2   Jakarta      Ya

Mean usia: 35.9
Median usia: 35.0

   usia  usia_median  usia_mean
0  25.0         25.0     25.000
1  32.0         32.0     32.000
2   NaN         35.0     36.125
3  45.0         45.0     45.000
4  28.0         28.0     28.000
5  51.0         51.0     51.000
6  38.0         38.0     38.000
7   NaN         35.0     36.125
8  29.0         29.0     29.000
9  41.0         41.0     41.000

Menggunakan MinMaxScaler

In [45]:
from sklearn.preprocessing import MinMaxScaler
df_minmax = pd.DataFrame(data)
df_minmax['usia'] = df_minmax['usia'].fillna(df_minmax['usia'].median())
df_minmax['pendapatan'] = df_minmax['pendapatan'].fillna(df_minmax['pendapatan'].median())

X_mm = df_minmax.drop(columns=['membeli'])
y_mm = df_minmax['membeli']

X_mm['pendidikan'] = X_mm['pendidikan'].map({'SMA': 0,'S1': 1,'S2': 2})

X_mm = pd.get_dummies(X_mm,columns=['kota'],dtype=int)
y_mm = y_mm.map({'Tidak': 0,'Ya': 1})

from sklearn.model_selection import train_test_split
X_train_mm, X_test_mm, y_train_mm, y_test_mm = train_test_split(X_mm,y_mm,test_size=0.3,random_state=42)

num = ['usia', 'pendapatan', 'pendidikan']
mm = MinMaxScaler()
X_train_mm[num] = mm.fit_transform(X_train_mm[num])
X_test_mm[num] = mm.transform(X_test_mm[num])
print("X_train setelah MinMaxScaler:")
display(X_train_mm.describe())

X_train setelah MinMaxScaler:

,usia,pendapatan,pendidikan,kota_Bandung,kota_Jakarta,kota_Surabaya
count,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
mean,0.514286,0.398214,0.428571,0.428571,0.428571,0.142857
std,0.349660,0.367808,0.449868,0.534522,0.534522,0.377964
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.325000,0.125000,0.000000,0.000000,0.000000,0.000000
50%,0.500000,0.287500,0.500000,0.000000,0.000000,0.000000
75%,0.725000,0.625000,0.750000,1.000000,1.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

Menambahkan kolom kategorikal baru

In [47]:
df_kategori = pd.DataFrame(data)
df_kategori['status_kerja'] = ['Tetap','Tetap','Kontrak','Tetap','Kontrak','Tetap','Tetap','Kontrak','Kontrak','Tetap']

display(df_kategori)
df_kategori_encoded = pd.get_dummies(df_kategori,columns=['status_kerja'],dtype=int)
display(df_kategori_encoded)

   usia  pendapatan pendidikan      kota membeli status_kerja
0  25.0   4000000.0        SMA   Bandung   Tidak        Tetap
1  32.0   7500000.0         S1   Jakarta      Ya        Tetap
2   NaN   5200000.0        SMA   Bandung   Tidak      Kontrak
3  45.0  12000000.0         S2  Surabaya      Ya        Tetap
4  28.0   4800000.0        SMA   Jakarta   Tidak      Kontrak
5  51.0  15000000.0         S2  Surabaya      Ya        Tetap
6  38.0   8100000.0         S1   Jakarta      Ya        Tetap
7   NaN   6300000.0         S1   Bandung   Tidak      Kontrak
8  29.0         NaN        SMA   Bandung   Tidak      Kontrak
9  41.0   9900000.0         S2   Jakarta      Ya        Tetap

,usia,pendapatan,pendidikan,kota,membeli,status_kerja_Kontrak,status_kerja_Tetap
0,25.0,4000000.0,SMA,Bandung,Tidak,0,1
1,32.0,7500000.0,S1,Jakarta,Ya,0,1
2,NaN,5200000.0,SMA,Bandung,Tidak,1,0
3,45.0,12000000.0,S2,Surabaya,Ya,0,1
4,28.0,4800000.0,SMA,Jakarta,Tidak,1,0
5,51.0,15000000.0,S2,Surabaya,Ya,0,1
6,38.0,8100000.0,S1,Jakarta,Ya,0,1
7,NaN,6300000.0,S1,Bandung,Tidak,1,0
8,29.0,NaN,SMA,Bandung,Tidak,1,0
9,41.0,9900000.0,S2,Jakarta,Ya,0,1

Mengapa fit_transform pada latih dan transform pada uji?

`fit_transform()` digunakan pada data latih karena scaler perlu mempelajari parameter dari data latih terlebih dahulu. Pada StandardScaler, parameter tersebut berupa nilai mean dan standar deviasi.

Setelah parameter diperoleh dari data latih, data uji hanya diproses menggunakan `transform()` dengan parameter yang sama. Data uji tidak boleh digunakan untuk melakukan `fit` karena hal tersebut dapat menyebabkan data leakage, yaitu informasi dari data uji masuk ke dalam proses pembelajaran preprocessing.

Oleh karena itu, proses yang benar adalah:

X_train → fit_transform()

X_test → transform()

Dengan cara ini, preprocessing pada data uji tetap menggunakan informasi yang diperoleh dari data latih saja.

Refleksi
1. Mengapa urutan “split dulu, baru scaling” penting?

  Urutan “split dulu, baru scaling” penting untuk mencegah terjadinya data leakage. Data harus dibagi terlebih dahulu menjadi data latih dan data uji. Setelah itu, scaler di-fit hanya menggunakan data latih.
  Pada data latih digunakan fit_transform() karena scaler perlu mempelajari parameter dari data latih. Sedangkan pada data uji hanya digunakan transform() menggunakan parameter yang telah diperoleh dari data latih.
  Dengan urutan tersebut, informasi dari data uji tidak digunakan dalam proses preprocessing data latih.

2. Kapan label encoding dan kapan one-hot encoding?

Label encoding digunakan ketika kategori memiliki urutan atau tingkatan tertentu. Pada praktikum ini, kolom `pendidikan` menggunakan ordinal encoding karena memiliki tingkatan SMA, S1, dan S2, yang kemudian dipetakan menjadi 0, 1, dan 2.
One-hot encoding digunakan untuk kategori nominal yang tidak memiliki urutan. Pada praktikum ini, kolom `kota` menggunakan one-hot encoding karena kategori Bandung, Jakarta, dan Surabaya tidak memiliki tingkatan tertentu.

3. Apa perbedaan normalisasi dan standarisasi?

Normalisasi merupakan proses penskalaan data ke rentang tertentu, misalnya 0 sampai 1. Pada latihan mandiri, proses ini dilakukan menggunakan `MinMaxScaler`.
Standardisasi merupakan proses mengubah data berdasarkan rata-rata dan standar deviasi sehingga data memiliki skala yang terstandarisasi. Pada praktikum utama, proses ini dilakukan menggunakan `StandardScaler`.
Dengan demikian, normalisasi dan standardisasi sama-sama digunakan untuk melakukan penskalaan fitur, tetapi metode dan hasil transformasinya berbeda.